name: BanItem
author: Ghast
version: 2.2
api: [1.0.0, 2.0.0]
main: Ghast\BanItem\Main
load: POSTWORLD
commands:
  banitem:
    description: "BanItem main command."
    permission: banitem.command.banitem
    usage: §f•§a>>§bGhi §e/banitem ban [ID Item]§b Để Ban Item. Ghi §e/banitem unban [ID Item]§b Để Un Ban Item. Ghi §e/banitem list§b Để Xem Danh Sách Item Đã Ban
permissions:
  banitem:
    default: false
    description: "Cấm Vật Phẩm Bạn Muốn Cấm"
    children:
      banitem.bypass:
        default: false
        description: "Cho Phép Sử Dụng Vật Phẩm Bị Cấm"
      banitem.command:
        default: false
        description: "Cho Phép Sử Dụng Tất Cả Lệnh /banitem"
        children:
          banitem.command.banitem:
            default: op
            description: "Cho Phép Sử Dụng Lệnh /banitem"